export enum EMessagePattern {
  CREATE_USER = 'CREATE_USER',
  DETAIL_USER = 'DETAIL_USER',
  LIST_USER = 'LIST_USER',
  DELETE_USER = 'DELETE_USER',
  EDIT_USER = 'EDIT_USER',
  AUTH_LOGIN = 'AUTH_LOGIN',
  GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN',
}
