export enum EMessagePattern {
  CREATE_EXAMPLE = 'CREATE_EXAMPLE',
  DETAIL_EXAMPLE = 'DETAIL_EXAMPLE',
  LIST_EXAMPLE = 'LIST_EXAMPLE',
  DELETE_EXAMPLE = 'DELETE_EXAMPLE',
  EDIT_EXAMPLE = 'EDIT_EXAMPLE',
}
